# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, bundle ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bundle:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2

      - name: Bundle Self-Executing Applications
        run: python package.py

      - name: Zip Release Archive
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          path: dist
          filename: PyMS-${{ matrix.os }}.zip

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: PyMS-${{ matrix.os }}
          path: PyMS-${{ matrix.os }}.zip
